spring.application.name=backend

# Conexion compatible con entorno local y Railway (Produccion)
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:link_and_celebrate}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER:JeremyAquino}
spring.datasource.password=${MYSQLPASSWORD:JEREMY1012.}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect